### ISSUE TITLE
Feat: Allow user to select GPU to run moose

### ISSUE THREAD

**Issue by LalithShiyam** [QIMP-Team/MOOSE#1]
Allow users to select the GPU to run moose. Makes a lot of sense if the user has a large server. Would be pivotal for multimoose.

- @LalithShiyam to develop the prototype
- @Keyn34 to test it

**Comment by chris-clem** [comment]
For now, you could let users know that they can do it with `CUDA_VISIBLE_DEVICES=3 moose -f /home/user/Data/Patients_moose` where `CUDA_VISIBLE_DEVICES` is the GPU number.

**Comment by LalithShiyam** [comment]
Cool! closing this as its clear now @chris-clem !
