### ISSUE TITLE
Bug: Small Intestine/Necrotic tumor tissue missclassified as bladder

### ISSUE THREAD

**Issue by KCHK1234** [QIMP-Team/MOOSE#21]
Fluid dense tissue surrounding the bladder often delineated as bladder while bladder delineation often only partial, probably hard to fix due to many instances of gravity dependend ascites in malignancies and cervical cancers as cohort.
All instances recorded

**Comment by LalithShiyam** [comment]
@josefyu : I agree with @KCHK1234, lets make sure we segment the bladder from the PET and not the CT. And frankly `moose` is just for FDG now. So this shouldn't be a problem.

**Comment by josefyu** [comment]
so right now, I am segmenting FALCON (siemens dataset 4 F, 4 M, 14 sequences), and here I use PET to delineate the bladder.
