### ISSUE TITLE
Bug: Nasal mucosa as skeletal muscle 

### ISSUE THREAD

**Issue by KCHK1234** [QIMP-Team/MOOSE#22]
In case of mucosal congestion in the nasal cavity and paranasal sinuses -> missclassification as skeletal muscles. 
This appears often but I think the effects are minor, hence MINOR bug.
All instances recorded

**Comment by LalithShiyam** [comment]
@KCHK1234 : would you be kind enough to verify, once @josefyu does the corrections?
