### ISSUE TITLE
Analysis request: MOOSE + PET-Parameter extraction of PCA cohort

### ISSUE THREAD

**Issue by KCHK1234** [QIMP-Team/MOOSE#23]
Analysis request for prostate cancer cohort as follows:

- [x] MOOSE cohort -> Validation of Segmentations by me
     - [ ] Extract PET-Parameters from MOOSEd Segments 
- [x ] Delete all hand drawn PET-Segmentations starting with cubic* 
- [ ] Merge all the remaining Segmentations (pb*, sv*, pln*...) on a patient level by the following convention:
    - [ ] all Segmentations to a Master_VOI  -> extract PET-Parameters (SUVmax, mean... + Metabolic Tumor volume) 
    - [ ] VOIs named: _pb* + sv*_ -> _Prostate_Sum_VOI_ -> extract PET-Parameters (SUVmax, mean... + Metabolic Tumor volume)
    - [ ] VOIs named: _dln* + pln* + rln*_ -> _Lymph_node_Sum_VOI_ -> extract PET-Parameters (SUVmax, mean... + Metabolic Tumor volume)
    - [ ] VOIs named: _bone*_ -> _Bone_Sum_VOI_ -> extract PET-Parameters (SUVmax, mean... + Metabolic Tumor volume)
    - [ ] VOIs named: _adrenal* + liver* + pleura* + lung* + rectum* + skin* + peritoneal* + org* + organ* + psoas* + testis* + lung* + cavern*_ -> _Organ_Sum_VOI_ -> extract PET-Parameters (SUVmax, mean... + Metabolic Tumor volume)

**Comment by KCHK1234** [comment]
Ok, so I updated the segmentation names and the merging conventions. 
So * ofc is a wildcard since many patients have i.e. Bone_1 to Bone_n....
Thank you buddy!

**Comment by LalithShiyam** [comment]
@KCHK1234: prostate cancer stuff has been moose'd. I will work on the tumour merge tomorrow (24 Fri, 2022)
