### ISSUE TITLE
BUG: Brain label error still persists

### ISSUE THREAD

**Issue by josefyu** [QIMP-Team/MOOSE#25]
Need to manually start again:

Calculated SUV image for SUV extraction!
- Brain found in field-of-view of PET/CT data...                                                             
- Cropping brain from PET image using the aligned CT brain mask
Traceback (most recent call last):
  File "/usr/local/bin/moose", line 214, in <module>
    cropped_pet_brain = iop.crop_image_using_mask(image_to_crop=pet_file[0],
  File "/home/mz/Documents/Softwares/MOOSE-V.1.0/src/imageOp.py", line 228, in crop_image_using_mask
    bbox = np.asarray(label_shape_filter.GetBoundingBox(1))
  File "/usr/local/lib/python3.8/dist-packages/SimpleITK/SimpleITK.py", line 36183, in GetBoundingBox
    return _SimpleITK.LabelShapeStatisticsImageFilter_GetBoundingBox(self, label)
RuntimeError: Exception thrown in SimpleITK LabelShapeStatisticsImageFilter_GetBoundingBox: /tmp/SimpleITK-build/ITK-prefix/include/ITK-5.2/itkLabelMap.hxx:151:
ITK ERROR: LabelMap(0x9547bd0): No label object with label 1.

**Comment by chris-clem** [comment]
Hello,

I am experiencing the same problem. Is there a way to solve it?

Thanks!

**Comment by LalithShiyam** [comment]
Hi @chris-clem, does your PET image have a brain in the field of view? If not, kindly remove the PET DICOM folder and simply just run the CT. Ideally, it should work now.

**Comment by chris-clem** [comment]
Sorry for the late response. That was indeed the problem, thank you!
