### ISSUE TITLE
BUG: - Provided data possibly not in DICOM format in folder

### ISSUE THREAD

**Issue by Ompsda** [QIMP-Team/MOOSE#40]

**Comment by LalithShiyam** [comment]
Hello did you manage to solve this? 
I assume you ran MOOSE multiple times without cleaning the dataset. The main folder should just have PT and CT dicom folders. No json files :)

**Comment by Ompsda** [comment]
Yes, thank you!

**Comment by LalithShiyam** [comment]
Great, please let me know if you have further issues :)!
