### ISSUE TITLE
Same error as issue 41

### ISSUE THREAD

**Issue by penguin1109** [QIMP-Team/MOOSE#48]
I am currently trying to run your MOOSE software on the PET/CT DICOM Images.
However, although I the RESULTS_FOLDER variable has been set, the same `index error` as issue 41 seems to occur.

Might there be any possible reasons for this?
My data folder is
```
base_folder
 |_ 01
    |- CTIMAGE
       |- xx.dcm 
       ..
    |- PETIMAGE

```
and I have run the `moose -f base_folder` command.

Thanks

**Comment by LalithShiyam** [comment]
Hi there, do you have enough RAM?

**Comment by penguin1109** [comment]
I'm sure I have enough RAM - can it be the cause of this issue??

**Comment by LalithShiyam** [comment]
Sure, there are many reasons why this can fail. 
- not enough RAM (256GB?), if your datasets are huge. 
- PET has no brain in the FOV 
- environment variables not set. 
- sometimes if there are spaces in the folder 

If you have enough RAM, can you just try it with CT? Just remove the PT folder for now. And see if it works. 
If it still doesn't work, I am happy to look at the anonymized data (if thats ok).

**Comment by penguin1109** [comment]
Well, I found that my RAM was only 64GB.. 
Would it be possible to manually get segmentation results from only the abdominal organs with limited memory? (This is what I actually need)

**Comment by penguin1109** [comment]
Thanks so much!
Can you not close this comment for a while???
I am trying to try out your first solution (using `nnUNet_predict`), but my GPU is full.

**Comment by penguin1109** [comment]
Actually, I have tried out the `NNUNet_predict -t 123`, but first, because
of the RAM memory, the ssh server seemed to have crashed as you told me.
Also, I was not able to find where the segmented map is supposed to be
saved. (I actually cannot understand why the process has to take the RAM
memory - I would appreciate it if you could explain the reason for me?)

If it is possible, if I send you the PET/CT zip file (it contains 54
cases), could you possibly get the inference results for me???
And since the data is actually private, I wish you would be able to delete
the files after the process is finished! (Kinda worried because it is
the patient's data )


I'll be looking forward for your reply!

Thanks.
Jihye Lee

**Comment by LalithShiyam** [comment]
Sure :)

**Comment by penguin1109** [comment]
Thank you so much!!!!!!!
This organ segmenting is the essential step for making the pseudo label of
prostate cancer, and most high dose CT segmentation models really didn't
make good results on low dose PET/CT images, so I was so glad to find your
work!!

https://drive.google.com/file/d/1Tj6CI5b_imA1d_LWKF0DKISKT0brniga/view?usp=sharing

The gdrive link above contains the data in zip file!!
Would it be possible to get the result of a single sample before all the
process ends????
Thanks again !

Jihye Lee

**Comment by penguin1109** [comment]
Does the data I have given you process well without any errors??
Again, thanks so much for your effort!

**Comment by LalithShiyam** [comment]
Hi Jihye, I am downloading your dataset now, I will run it and keep you posted via your mail.

**Comment by penguin1109** [comment]
Thanks a lot!
I’m concerned that this might be too time consuming for you..

**Comment by Keyn34** [comment]
Hello @penguin1109,

You can download the segmentation results of MOOSE here: https://filesender.aco.net/?s=download&token=73cdc98e-f5ed-40e1-bb0d-37490be1c62c

Please note that I had to remove the PET folder, as MOOSE does not support PSMA. The segmentations are in the labels folder within the respective MOOSE-X folder.

**Comment by penguin1109** [comment]
I am so grateful for the PERFECT RESULTS!!!!
It's so surprising that the difference of pretrained models trained on
either PET/CT images or plain CT images are so different!
I have trained some segmentation models on the BTCV dataset, and though it
worked well on that data, it failed to work properly on ours PSMA PET/CT
dataset.

I am currently doing a research on segmenting organs from PET images, and
do you suppose it would at least be possible?
What I am planning to try out on is PET to CT style transfer and
segmentation task at the same time!! I was so impressed by your software
that I wanted to get some small advice from you..!! :)

Again, thank you so so so much for the fabulous results... Without your
help, I could not have stepped forward on the research project..

Jihye Lee

**Comment by LalithShiyam** [comment]
Thank you @Keyn34 for sending @penguin1109 her data back. 

@penguin1109 every PET study comes with a CT. You can just transfer the CT segmentations back to the PET, since they are acquired fairly together. If you are just interested in getting the abdominal organs, I would just use CT and transfer the segmentation to the corresponding PT, using the reslice filters from simpleitk. PT is useful when you want to segment something like prostate lesions/tumors. 

This would be my two cents.

**Comment by penguin1109** [comment]
My research topic is segmenting all organs only with the PET since there
seems to be for my information, no research done on it!
So I was planning to train my model to get segmented results of all organs
only with the PET inputs, which was why I needed labels generated from the
ct images!!

Do you possibly think this would be at least possible??

Thanks so much for your help!

**Comment by LalithShiyam** [comment]
Sure it's possible and there has been research done on it. I would suggest you to google the PSMA-HORNET paper. They did the segmentations based on only PT as far as I remember.

**Comment by penguin1109** [comment]
Oh I see!! I will check out that paper!

I really appreciate all the help you gave me! :D
I will be looking for your MOOSE version 2!😆

Jihye Lee

**Comment by LalithShiyam** [comment]
Stay tuned ✌🏼cool things underway!

**Comment by LalithShiyam** [comment]
Hi @penguin1109, moosev2 is online ;) just thought i would reach out to you!
