### ISSUE TITLE
BUG: dask[distributed] package requires python3.9.2 not python 3.9.0 

### ISSUE THREAD

**Issue by Ottomuzik2203** [QIMP-Team/MOOSE#59]
**Describe the bug**
When we try to install moosez in a python3.9 environment (as mentioned in ReadMe). The installation works fine but when we try to run moosez via `moosez -h`, we encounter issues as dask[distributed] mandates python 3.9.2 or above, please refer the known error here: https://github.com/dask/distributed/issues/7956.
 
**To Reproduce**
1. Create moose-env as suggested in readme
2. `pip install moosez`
3. and type `moosez -h`

**Expected behavior**
Please suggest users to use python 3.9.2 or above.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Comment by LalithShiyam** [comment]
LOL @Ottomuzik2203, great find! Will fix it right away!

**Comment by LalithShiyam** [comment]
Sorted @Ottomuzik2203!
