### ISSUE TITLE
Adding cerebral region segmentation function

### ISSUE THREAD

**Issue by Samnonstop** [QIMP-Team/MOOSE#80]
Problem description:
In your MOOSE paper (DOI: 10.2967/jnumed.122.264063), it introduced that a model was trained to segment 83 brain subregions from PET data combined with T1-weighted MR images. However in this repository the only PET segmentation model provided is for tumors in FDG PET, and there is no sign of that cerebral region segmentation model.

Desired behavior:
The aforementioned model for segmenting 83 brain subregions is present.

Alternatives:
Or probably this model is already uploaded. Please point me to where it could be found.

Thank you very much for providing such a powerful image processing tool!

**Comment by LalithShiyam** [comment]
Hi @Samnonstop, many thanks for the message. It is true that moosev1, had the 83 brain segmentations from PET. We removed it in moosev2, due to less usage.

Anyway, we are happy to help you. Would you be kind enough to tell us if your input is just FDG PET brains?

**Comment by Samnonstop** [comment]
Sure, thank you so much for the response. I have FDG PET/MR images as input. The intention was to segment the PET images using MOOSE and then transform the atlas to the MRI volumes.

**Comment by LalithShiyam** [comment]
Great, so it's just brain PET/MR right?

**Comment by Samnonstop** [comment]
Yes. The FOV only contains the patient brain.

**Comment by LalithShiyam** [comment]
Hi @Samnonstop fantastic. We will include the moosev1 model in moosev2. But this will take a couple of days - would that be OK? We need to train it.

@mprires would you be kind enough to take the OG moosev1 training data and train it with `no_mirroring` trainer, since the brain has left and right sides?

**Comment by Samnonstop** [comment]
> Hi @Samnonstop fantastic. We will include the moosev1 model in moosev2. But this will take a couple of days - would that be OK? We need to train it.
> 
> @mprires would you be kind enough to take the OG moosev1 training data and train it with `no_mirroring` trainer, since the brain has left and right sides?

Thank you so much! Please take your time, since this is not an urgent need and you are volunteering to help out. Looking forward to trying the brain region segmentation tool.

**Comment by Samnonstop** [comment]
> Hi @Samnonstop I will get the training started today and will update you when it's available

Really appreciate your help and time.

**Comment by LalithShiyam** [comment]
Hi @Samnonstop training done, now testing 🙌🏽

**Comment by LalithShiyam** [comment]
Hi @Samnonstop your model is ready to use!

**Comment by Samnonstop** [comment]
> Hi @Samnonstop your model is ready to use!

Thank you so much for your kind help! You guys are so efficient. By the way, how could I download the new model?

**Comment by Samnonstop** [comment]
> > Hi @Samnonstop your model is ready to use!
> 
> Thank you so much for your kind help! You guys are so efficient. By the way, how could I download the new model?

No worries. I just replaced the old code files with your updated ones and the clin_pt_fdg_brain_v1 model is now downloading. Will close this issue once it is tested on my pc.

**Comment by Samnonstop** [comment]
> > > Hi @Samnonstop your model is ready to use!
> > 
> > 
> > Thank you so much for your kind help! You guys are so efficient. By the way, how could I download the new model?
> 
> No worries. I just replaced the old code files with your updated ones and the clin_pt_fdg_brain_v1 model is now downloading. Will close this issue once it is tested on my pc.

The new model successfully segmented PET brain images in my environment and the results look promising. Thank you a lot for your great support as well as providing such a powerful segmentation tool! I'm closing this issue now.

**Comment by LalithShiyam** [comment]
Hi @Samnonstop many thanks for your kind words. Happy it worked out well. Leave us a star if you find MOOSE useful!
