### ISSUE TITLE
running MOOSE issue

### ISSUE THREAD

**Issue by Ompsda** [QIMP-Team/MOOSE#83]
Dear MOOSE group,

I am trying to use moose for the segmentation of a patient's CT data using the bellow commands but I get an error suggesting there is no moose complying subject. Is this the write way to run moose? any suggestions, please?

    (moose-env) PATH-TO\moose-env>moosez -d "C:\\Users\NAME\\Box\SEG\\CLINICAL\\S1\\AC-CT"  -m clin_ct_organs

 Imaging: Clinical | Modality: CT | Tissue of interest: Organs
 Required modalities: ['CT'] |  No. of modalities: 1 | Required prefix for non-DICOM files: ['CT_']
 Warning: Subjects which don't have the required modalities [check file prefix] will be skipped.
 CUDA is available on this device with 2 GPU(s). Predictions will be run on GPU.

 🌐 MODEL DOWNLOAD:

 A local instance of Dataset123_Organs has been detected.

 🔍 STANDARDIZING INPUT DATA TO NIFTI:

 Processing subjects... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
 Standardization complete.
 Number of moose compliant subjects: 0 out of 0
 ❌ No moose compliant subject found to continue! 💡 See: https://github.com/QIMP-Team/MOOSE#directory-structure-and-naming-conventions-for-moose-%EF%B8%8F

Thank you

**Comment by LalithShiyam** [comment]
Hi @Ompsda It looks like you don't have moose compatible directory. Can you please share your folder structure, so that I can pinpoint the error?

**Comment by Ompsda** [comment]
thank you for the prompt response:
C:\Users\hamdi.m\Box\Vision_E7tools\clinical_data\S1

![image](https://github.com/QIMP-Team/MOOSE/assets/52762166/18f4e039-84a9-480a-9a31-e3179252e3a6)

**Comment by Ompsda** [comment]
I have specified the CT directory according to the readme.
Thanks

**Comment by Ompsda** [comment]
As far as I know, I have already tried using what is described in the readme file. It 

Thanks,

**Comment by LalithShiyam** [comment]
Hi @Ompsda I am afraid not. I looked at the folder structure you shared and it is definitely not the one posted in the readme. 

You need to have a root folder, and inside it you need to have your individual subject folders. And each subject folder should have their own PT and CT (can be named anything). And keep in mind this subject folder ideally shouldn't have anything other than the PT and the CT. Right now you have a bunch of other files (your python scripts and other stuff). The input for moosez when you use it as a command line is pretty much the root directory which contains the subject folders and NOT the CT folder of the individual subject. 

Hope it helps.

**Comment by Keyn34** [comment]
Hey @Ompsda,

Create a folder that you call `subjects` in `C:\Users\hamdi.m\Box\Vision_E7tools\clinical_data`. In the folder `subjects`, create a folder called `S1`. You place your `AC-CT` and `AC-PET` folder inside folder `S1`. Then you run `moosez` again and supply the `-d` argument with the path to the `subjects` folder: 
`moosez -d C:\Users\hamdi.m\Box\Vision_E7tools\clinical_data\subjects -m clin_ct_organs`

**Comment by LalithShiyam** [comment]
Hi @Ompsda Kindly let us know if you managed to run moose :)

**Comment by Ompsda** [comment]
Hi Guys, I was able to run moose now. Many thanks for your help. I truly appreciate it.

**Comment by LalithShiyam** [comment]
Fantastic @Ompsda, then I will close this issue 🍡 !

Have fun MOOSE-ing.
