### ISSUE TITLE
Export segmentations as RT Structure Sets

### ISSUE THREAD

**Issue by rullator** [QIMP-Team/MOOSE#89]
Hi guys,

have you ever thought about exporting the calculated segmentations as RT structure sets?
It could enhance the MOOSE usage on non-NIfTI imaging software suites :)

Best
Michael

**Comment by LalithShiyam** [comment]
Hi @rullator, yes we did. But not sure how great it works, as we tested it only on slicer. You can use this package which we cobbled up: https://github.com/LalithShiyam/nifti2dicom! 

Ah, also it can convert a 4d moco nifti to dicom as well ;) 

Give it a shot and let us know!

**Comment by rullator** [comment]
OK, thanks for the suggestion!

This can be closed
