### ISSUE TITLE
BUG: Problems with clin_ct_body

### ISSUE THREAD

**Issue by rullator** [QIMP-Team/MOOSE#91]
Within the most recent version of MOOSE I cannot use the "clin_ct_body" prediction - even in cases, where prediction worked fine previously. Other models work fine (as usual).
MOOSE runs into the following error:

```
â ´ [1/1] Running prediction for *** using clin_ct_body...Traceback (most recent call last):
  File "/.../MOOSE2.0/moose-env/bin/moosez", line 8, in <module>
    sys.exit(main())
  File "/.../MOOSE2.0/moose-env/lib/python3.9/site-packages/moosez/moosez.py", line 198, in main
    predict.predict(model_name, input_dir, output_dir, accelerator)
  File "/.../MOOSE2.0/moose-env/lib/python3.9/site-packages/moosez/predict.py", line 78, in predict
    postprocess(original_image_files[0], output_dir, model_name)
  File "/.../MOOSE2.0/moose-env/lib/python3.9/site-packages/moosez/predict.py", line 131, in postprocess
    predicted_image = file_utilities.get_files(output_dir, '.nii.gz')[0]
IndexError: list index out of range
```

Does anyone else experience that error?

**Comment by LalithShiyam** [comment]
Hi @rullator, can you tell me the version number of moose. I will have a look. We are using the body mask religiously for other tools and we didn’t have a problem.

**Comment by rullator** [comment]
`Requirement already satisfied: moosez in ./moose-env/lib/python3.9/site-packages (2.3.4)`

PS: all other models also run fine..

**Comment by LalithShiyam** [comment]
Ok let me see what it is! But I can do this only tomorrow, as today is a holiday in Austria and my Remote Desktop doesn’t work from morning. Sorry about this 😬

**Comment by rullator** [comment]
No problem!!
Please also enjoy your weekend! ;)

**Comment by LalithShiyam** [comment]
Hi @rullator, I am not able to reproduce this error... can you give me more information about the OS, python env?

**Comment by lescientifik** [comment]
Hi there,

Same exact problem here, freshly installed Ubuntu 22 LTS, fresh install of moose.

However i am running on a laptop below recommended system requirements (8gb ram, no gpu). I tried directly from dicom directory, from .nii and from .nii.gz.

Could system specs have something to do with it ?

**Comment by LalithShiyam** [comment]
Hi there, can you try it with a fresh environment with python3.10? Just trying to see if the python version with `nnunetv2` is a problem.

**Comment by lescientifik** [comment]
hi again,

already on Python 3.10.12. As I said, the install is as fresh as it can get, the laptop was freshly re-installed to test this gorgeous package :)

**Comment by LalithShiyam** [comment]
LOL, thank you for the kind words. I didn't know it was 3.10 already, usually this results in issues. As a follow up question, can you use other models like @rullator? or nothing works in your case?

**Comment by lescientifik** [comment]
ok, my bad

I was running the "clin_ct_organs" and not "clin_ct_body" as OP.

Clin_ct_body did work for me without any error (and relatively fast for mobile cpu inference!)

Clin_ct_organs do not. Do you want me to open another issue or do we keep it on this track ? The error message is exactly the same as OP.

**Comment by LalithShiyam** [comment]
I think we can leave it here. Can you send me the screenshots of the files that are generated intermittently. Also what is the size of the images?
 
For organ inferences, the images are chunked to 3 parts. It can happen that it might be a memory issue since it's just 8GB. But if the chunk files are generated (folder where nifti CT images are stored), it should be fine. Please let me know.

**Comment by lescientifik** [comment]
the volume is 512x512x137. I did not find chunk files generated, but it is a bit cumbersome to stare more than 10 minutes at my screen waiting for something to happen ;)

Running moose alone (understand, with Chrome the "RAM eater" closed), i am not getting any error, but the process seems to hang, the spinner spins, but my 4 cores are idling, and RAM is still used. I suspect i am quite limited by my hardware. I will let it run overnight just to see if something happens.

Anyways, I will try to get my hand on something more powerful. I consider this resolved for now. If you do not hear from me soon, consider I am a happy mooser ;)

PS: as a side note, it would be great if you could give us more details about the dataset used to train each model to get a better grasp of what could (or could not) go wrong when using it on real data. I am planning to use Moose for some research (i am a nuclear physician), and read with great interest your original publication in the JNM. Maybe a follow up paper would be nice ?^^

**Comment by LalithShiyam** [comment]
_I did not find chunk files generated_

I think it might be the issue with 'dask', we use chunking to make sure your RAM doesn't get loaded. If the doesn't doesn't do chunking, there is not files for nnunet to infer. This makes it clear why clin_ct_body works, as it doesn't have any chunking mechanism for it :D!

And many thanks for the kind words regarding the JNM paper. Shoot me a mail, I will share the details of the training data: lalith.shiyamsundar@meduniwien.ac.at

**Comment by lescientifik** [comment]
Hi again,

i don't think Dask is the culprit here. I have looked at your code, and here is the condition to be defined as large_image

`return np.prod(image_shape) > MATRIX_THRESHOLD and image_shape[2] > Z_AXIS_THRESHOLD`

My image has a z_axis of 137 (Z_AXIS_THRESHOLD=200) so it does not satisfy the second condition, and is_large_image is False. Thus, both path (ct_body and ct_organs) of image resampling are equivalent: no dask involved.

PS: will send you for sure an email tomorrow from the office! Thanks a lot !

**Comment by LalithShiyam** [comment]
Fantastic, now it might definitely be the 8 gb ram... let's hope it works on a bigger ram :)

**Comment by lescientifik** [comment]
with 32GB of RAM, works flawlessly!

clin_ct_PUMA seems way better than clin_ct_organs by the way!

Thanks a lot for this project!!

**Comment by rullator** [comment]
> Hi @rullator, I am not able to reproduce this error... can you give me more information about the OS, python env?

`> uname -r
4.18.0-477.27.1.el8_8.x86_64`

`> cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.8 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.8 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"`

`>python --version
Python 3.9.7`

I also just updated MOOSE to 2.3.5, but the problem persists.

I will try a fresh install.
I will also check a fresh install of Moose

**Comment by rullator** [comment]
OK, a fresh install works and the problem is gone - perfect! :)

**Comment by LalithShiyam** [comment]
Sorry guys, for the radio silence. I was out-of-town. I am happy that everything is solved. If not I am at your disposal again! 

Cheers for the active feedback and for actually updating the thread. Saves a lot of work from ourside.

Cheers,
Lalith
